<?php
    $config = Zend_Registry::get('config');
    echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle(" / © 2012-".date("Y"));?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <link rel="shortcut icon" href="/img/favicon.ico" >
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
        <?php echo $this->headMeta();?>
        <meta name="Document-state" content="Static"/>
        <meta name="URL" content="absolute_url"/>
        <meta name="Distribution" content="global"/>
        <meta name="Resource-type" content="document"/>
        <meta name="robots" content="all"/>
        <meta name="revisit-after" content="1 days"/>
        <?php
            foreach ($config->sharedStyles as $style)
            {
                $this->headLink()->appendStylesheet($style);
            }
            echo $this->headRevisionLink();
            foreach ($config->sharedScripts as $script)
            {
                $this->headScript()->appendFile($script);
            }
            echo $this->headRevisionScript();
        ?>
    </head>
    <body>
        <div class="wrapper">
            <div class="header">
                <h1><a href="/">Раздел пользователя</a><br />
                <a href="/admin">Раздел амдинистратора</a></h1>
                <a class="logout" href="/logout">Выйти из системы</a>
                <div class="menu">
                   <div class="block">
                       <a href="/user/update">Обновить свои данные</a><br />
                       <a href="/message">Сообщения</a>
                   </div>
                </div>
            </div>
            <div class="content">
               <?php echo $this->layout()->content;?>
            </div>
            <div class="footer">
               <?php echo date("Y");?> &copy; messenger
            </div>
        </div>
    </body>
</html>
