<fieldset>
    <legend>Добавить сообщение</legend>
    <form action="/message/add" method="post" class="add">
        <dl>
            <dt>
                <label for="to">Кому</label>
            </dt>
            <dd>
                <div class="input-over">
                    <?php echo $this->formText("to", isset($this->data) ? $this->data['to'] : null, array('class' => 'required'));?>
                </div>
                <?php if (isset($this->error['to'])):?>
                <ol class="error">
                    <?php foreach (array_values($this->error['to']) as $error) echo '<li>'.$error.'</li>';?>
                </ol>
                <?php endif;?>
            </dd>
            <dt>
                <label for="title">Заголовок</label>
            </dt>
            <dd>
                <div class="input-over">
                    <?php echo $this->formText("title", isset($this->data) ? $this->data['title'] : null, array('class' => 'required'));?>
                </div>
                <?php if (isset($this->error['title'])):?>
                <ol class="error">
                    <?php foreach (array_values($this->error['title']) as $error) echo '<li>'.$error.'</li>';?>
                </ol>
                <?php endif;?>
            </dd>
            <dt>
                <label for="text">Текст</label>
            </dt>
            <dd>
                <div class="input-over">
                    <?php echo $this->formTextarea("text", isset($this->data) ? $this->data['text'] : null, array('class' => 'required'));?>
                </div>
                <?php if (isset($this->error['text'])):?>
                <ol class="error">
                    <?php foreach (array_values($this->error['text']) as $error) echo '<li>'.$error.'</li>';?>
                </ol>
                <?php endif;?>
            </dd>
            <dt>
            </dt>
            <dd>
                <?php echo $this->formSubmit("submit", "Отправить");?>
            </dd>
        </dl>
    </form>
</fieldset>
